services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - playground-so

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - playground-so

networks:
  playground-so:
    driver: bridge